# Generated by Django 5.2.17 on 2026-08-27 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "retrieved_page_refs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{'study_page_id': ..., 'page_num': ...}, ...] — references StudyPage rows, not duplicated text.",
                    ),
                ),
                ("handbook_guide_snapshot", models.TextField(blank=True, default="")),
                ("augmented_prompt", models.TextField(blank=True, default="")),
                ("raw_model_response", models.TextField(blank=True, default="")),
                ("formatted_answer", models.TextField(blank=True, default="")),
                ("keywords_used", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DetectedStudyBoundary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_start", models.PositiveIntegerField()),
                ("page_end", models.PositiveIntegerField()),
                (
                    "suggested_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "included",
                    models.BooleanField(
                        default=True,
                        help_text="User can exclude a detected boundary before confirming. v1 does not support resizing page ranges.",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "page_start"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("keywords", models.JSONField(blank=True, default=list)),
                (
                    "condition_note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional free-text note. Conditional instructions already live inline in `text` (e.g. 'only if repeated-dose study') — this is not a separate rule engine.",
                        max_length=255,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_number", models.PositiveIntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("halted_cost_limit", "Halted (cost limit)"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("debugging", models.BooleanField(default=False)),
                ("split", models.BooleanField(default=False)),
                (
                    "question_set_snapshot",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Explicit redundant copy of the question set at run start, per decision 9 — in addition to prompt_config_version's QuestionSnapshot rows.",
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("llm_model", models.CharField(blank=True, default="", max_length=128)),
                ("total_input_tokens", models.PositiveBigIntegerField(default=0)),
                ("total_output_tokens", models.PositiveBigIntegerField(default=0)),
                ("total_api_calls", models.PositiveIntegerField(default=0)),
                ("total_latency_ms", models.FloatField(default=0.0)),
                ("estimated_cost_usd", models.FloatField(blank=True, null=True)),
                ("cost_limit_enabled", models.BooleanField(default=False)),
                ("cost_limit_usd", models.FloatField(blank=True, null=True)),
                ("halted_due_to_cost_limit", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="started_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LLMCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "node_name",
                    models.CharField(
                        choices=[
                            ("retrieve_guide", "Retrieve guide"),
                            ("generate", "Generate"),
                            ("formatter", "Formatter"),
                        ],
                        max_length=32,
                    ),
                ),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("latency_ms", models.FloatField(default=0.0)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("estimated_cost_usd", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_logs",
                        to="studies.answer",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_logs",
                        to="studies.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="studies.pipelinerun",
            ),
        ),
        migrations.CreateModel(
            name="PromptConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("intro_text", models.TextField()),
                ("few_shots_text", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_prompt_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptConfigVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField(unique=True)),
                ("intro_text", models.TextField()),
                ("few_shots_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="studies.promptconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="prompt_config_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="studies.promptconfigversion",
            ),
        ),
        migrations.CreateModel(
            name="QuestionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("keywords", models.JSONField(blank=True, default=list)),
                (
                    "condition_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "prompt_config_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_snapshots",
                        to="studies.promptconfigversion",
                    ),
                ),
                (
                    "source_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="studies.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="question_snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="answers",
                to="studies.questionsnapshot",
            ),
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "page_range",
                    models.JSONField(
                        blank=True,
                        help_text="List of 1-based page numbers, or null for the whole document.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("building_corpus", "Building corpus"),
                            ("indexing", "Indexing"),
                            ("running_questions", "Running questions"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_boundary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="studies",
                        to="studies.detectedstudyboundary",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "studies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="studies.study",
            ),
        ),
        migrations.CreateModel(
            name="StudyPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                (
                    "extraction_method",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("ocr", "OCR"),
                            ("fallback_text", "Fallback text"),
                        ],
                        default="text",
                        max_length=16,
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Unmodified pymupdf extraction — always kept as the fallback.",
                    ),
                ),
                ("cleaned_text", models.TextField(blank=True, default="")),
                (
                    "final_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What actually went into the corpus (may be OCR markdown).",
                    ),
                ),
                ("is_table", models.BooleanField(default=False)),
                ("is_toc", models.BooleanField(default=False)),
                ("ocr_attempted", models.BooleanField(default=False)),
                ("ocr_succeeded", models.BooleanField(default=False)),
                ("ocr_error", models.TextField(blank=True, default="")),
                ("ocr_duration_ms", models.FloatField(blank=True, null=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="studies.study",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number"],
            },
        ),
        migrations.CreateModel(
            name="UploadBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "split_requested",
                    models.BooleanField(
                        default=False,
                        help_text="The 'Split this PDF into multiple studies' checkbox value at upload time.",
                    ),
                ),
                (
                    "split_status",
                    models.CharField(
                        choices=[
                            ("not_applicable", "Not applicable"),
                            ("detecting", "Detecting"),
                            ("awaiting_confirmation", "Awaiting confirmation"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="not_applicable",
                        max_length=32,
                    ),
                ),
                ("split_error_message", models.TextField(blank=True, default="")),
                (
                    "split_params_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="e.g. {'minimum_page_for_split': 80, 'target_study_words': [...]}",
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="study",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studies",
                to="studies.uploadbatch",
            ),
        ),
        migrations.AddField(
            model_name="detectedstudyboundary",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detected_boundaries",
                to="studies.uploadbatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="promptconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="unique_active_prompt_config",
            ),
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(
                fields=("run", "question_snapshot"), name="unique_run_question_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinerun",
            constraint=models.UniqueConstraint(
                fields=("study", "run_number"), name="unique_study_run_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="studypage",
            constraint=models.UniqueConstraint(
                fields=("study", "page_number"), name="unique_study_page_number"
            ),
        ),
    ]
