# Generated by Django 5.2.17 on 2026-08-27 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="study",
            name="source_boundary",
        ),
        migrations.AddField(
            model_name="study",
            name="assessment_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Copied from source_corpus. Never assumed to be 'toxicity' — check this before describing a Study as a toxicity study, or before running it through the toxicity question set at all.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="detection_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Copied from source_corpus at confirmation, for convenient querying.",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="DetectedCorpus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "detection_type",
                    models.CharField(
                        choices=[
                            ("long_report_split", "Long report split"),
                            ("integrated_report_split", "Integrated report split"),
                            ("user_requested_split", "User-requested split"),
                            ("single_document", "Single document"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Proposed title — editable before confirming.",
                        max_length=255,
                    ),
                ),
                (
                    "assessment_category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="For an integrated-report corpus: the matched assessment type (e.g. 'toxicity', 'environmental', 'residue'). Blank for other detection types, or when not yet classified — never defaults to 'toxicity'.",
                        max_length=100,
                    ),
                ),
                (
                    "page_numbers",
                    models.JSONField(
                        default=list,
                        help_text="Every page number included in this corpus.",
                    ),
                ),
                (
                    "shared_page_numbers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Subset of page_numbers pulled from report-wide shared sections.",
                    ),
                ),
                ("preview_text", models.TextField(blank=True, default="")),
                (
                    "detection_warnings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="list[str] of detection uncertainty signals.",
                    ),
                ),
                (
                    "included",
                    models.BooleanField(
                        default=True,
                        help_text="User can exclude a detected corpus before confirming.",
                    ),
                ),
                (
                    "cached_docs",
                    models.JSONField(
                        default=list,
                        help_text="[{'content':..., 'metadata':{...}}, ...]",
                    ),
                ),
                ("cached_summary", models.JSONField(blank=True, null=True)),
                ("cached_title_page", models.JSONField(blank=True, null=True)),
                (
                    "cached_page_provenance",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Per-page extraction info (matches StudyPage's fields) for the 'single'/'split' paths.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_corpora",
                        to="studies.uploadbatch",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "detected corpora",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="study",
            name="source_corpus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="studies",
                to="studies.detectedcorpus",
            ),
        ),
        migrations.DeleteModel(
            name="DetectedStudyBoundary",
        ),
    ]
