# Generated by Django 5.2.17 on 2026-08-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0002_remove_study_source_boundary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadbatch",
            name="split_status",
            field=models.CharField(
                choices=[
                    ("not_applicable", "Not applicable"),
                    ("detecting", "Detecting"),
                    ("awaiting_confirmation", "Awaiting confirmation"),
                    ("confirmed", "Confirmed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="not_applicable",
                max_length=32,
            ),
        ),
    ]
