# Generated by Django 5.2.17 on 2026-08-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0003_alter_uploadbatch_split_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadbatch",
            name="detection_failure_history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{'retry_number', 'error_message', 'occurred_at'}, ...] — a permanent record of every detection failure, written whenever split_status becomes FAILED. Never cleared, even though split_error_message (the *active* error) is cleared when a retry begins.",
            ),
        ),
        migrations.AddField(
            model_name="uploadbatch",
            name="retry_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times corpus detection has been retried after a failure.",
            ),
        ),
    ]
